site_name: Rocket-args
repo_name: Xaaq/Rocket-args
repo_url: https://github.com/Xaaq/Rocket-args

markdown_extensions:
  - admonition
  - codehilite
  - markdown_include.include:
      base_path: docs

theme:
  name: material
  logo: "img/logo_mini.png"
  favicon: "img/logo_mini.png"

nav:
  - Home: index.md
  - Tutorial:
      - First steps: tutorial/first_steps.md
      - Arguments: tutorial/arguments.md
  - Contributing: contributing.md
